- name: "Install packages"
  apt:
    name:
    - "build-essential"
    - "python3"
    - "python3-dev"
    - "python3-pip"
    - "python3-venv"
    - "virtualenv"
    - "mercurial"
    - "bsdmainutils"
    - "luarocks"

- name: "Create buildbot user"
  user:
    name: buildbot
    comment: Buildbot worker
    home: "{{ buildbot_home }}"
    create_home: yes

- name: "Install/upgrade pip and buildbot-worker"
  become: yes
  become_user: buildbot
  pip:
    name:
    - pip
    - buildbot-worker
    state: latest
    virtualenv: "{{ buildbot_home }}"

- name: "Create buildbot worker"
  become: yes
  become_user: buildbot
  command:
  args:
    argv:
    - buildbot-worker
    - create-worker
    - "{{ inventory_hostname }}"
    - "{{ buildbot_master_ip }}:9989"
    - "{{ inventory_hostname }}"
    - "{{ lookup('password', 'credentials/'+inventory_hostname) }}"
    creates: "{{buildbot_home}}/{{inventory_hostname}}"
    chdir: "{{buildbot_home}}"
  environment:
    HOME: "{{ buildbot_home }}"
    PATH: "/usr/bin:/bin:{{ buildbot_home }}/bin"
    VIRTUAL_ENV: "{{ buildbot_home }}"

- name: "Create buildbot service file"
  template:
    src: buildbot.service
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: u=rw,go=r
  register: buildbot_service_file

- name: "Reload systemd"
  command:
  args:
    argv:
    - systemctl
    - daemon-reload
  when: buildbot_service_file is changed

- name: "Start buildbot worker"
  service:
    name: buildbot
    state: started
    enabled: yes
